// web/frontend/react/react_basic/habit-tracker/src/components/habitAddForm.jsx
import React, { Component } from 'react';

class HabitAddForm extends Component {

  formRef = React.createRef();
  inputRef = React.createRef();

  onSubmit = event => {
    event.preventDefault();
    const name = this.inputRef.current.value;
    name && this.props.onAdd(name);
    // this.inputRef.current.value = '';
    this.formRef.current.reset();
  }
  render() {
    return (
      <form ref={this.formRef} className="add-form" onSubmit={this.onSubmit}>
        <input ref={this.inputRef} type="text" className="add-input" placeholder="Habit"/>
        <button className="add-button">Add</button>
      </form>
    );
  }
}

export default HabitAddForm;

// web/frontend/vue/vue_basic/habit-tracker/src/components/HabitAddForm.vue
<template>
  <form class="add-form" @submit="onSubmit">
    <input type="text" v-model="name" class="add-input">
    <button class="add-button">Add</button>
  </form>
</template>
<script>
export default {
  data() {
    return {
      name: '',
    }
  },
  methods: {
    onSubmit: function (event) {
      event.preventDefault();
      this.$emit('add', this.name);
      this.name = '';
    }
  },
}
</script>
<style>
.add-input {
  font-size: 2rem;
}

.add-input {
  margin-right: 0.2em;
}

.add-button {
  height: 100%;
  font-size: 1.5rem;
  padding: 0.3em 0.5em;
  background-color: green;
  color: white;
}

</style>
